# Generated by Django 2.0.3 on 2018-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
