# Generated by Django 2.0.3 on 2018-03-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_show_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
