# Generated by Django 2.0.3 on 2018-03-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180320_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_rating',
        ),
    ]
