# Generated by Django 2.0.3 on 2018-03-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
